"""
Django settings for ERIDB project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u6an(b6^@a98oxpcb!!h0#_0n8#417el8+l-)+mg3v=el_4k&3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'db.apps.DbConfig',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ERIDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ERIDB.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'django',
        'USER': 'kont',
        'PASSWORD': 'kont',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
LANGUAGE_CODE = 'ru'
LANGUAGES = (
    ('ru', 'Russian'),
    ('en', 'English'),
)
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_L10N = False
DATETIME_FORMAT = 'd.m.Y, H:i'
USE_TZ = False
DEFAULT_CHARSET = 'utf-8'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


MEDIA_URL = '/'
# MEDIA_ROOT = '/media/sf_PROJECTS/ERIDB/db/files'
MEDIA_ROOT = '/K/ERIDB/'
STATIC_URL = '/static/'
# STATIC_ROOT = '/media/sf_PROJECTS/ERIDB/db'
STATIC_ROOT = '/K/ERIDB/db/'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
# email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = False
EMAIL_HOST = '192.168.0.30'
EMAIL_HOST_USER = 'sender@kontinent-spb.ru'
# EMAIL_HOST_PASSWORD = 'N1xQnefHjA'
EMAIL_PORT = 25
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# global vars
DEFAULT_FOOTPRINT = 'defaultfootprints.PcbLib'
DEFAULT_UGO = 'defaultugo.SchLib'
DEFAULT_UGO_CSV = 'defaultugo.csv'
ALTIUM_PATH = 'U:\ERIDB\Altiumlibs\\'

DEBUG_MODE = True
DATA_CONNECT_DB_DJANGO = "dbname='django' user='kont' host='localhost' password='kont'"
DATA_CONNECT_DB_ALTIUM = "dbname='altium' user='kont' host='localhost' password='kont'"

# Celery settings
CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"
